"""Image evidence parser.

It accepts JSON sidecar files generated by OCR or image-region systems.
Each item becomes drawing evidence with bounding boxes and page anchors.
"""

from __future__ import annotations

from pathlib import Path

from llm_trace.parsers.evidence_builder import build_evidence
from llm_trace.schemas import Evidence
from llm_trace.utils.io import read_json


class ImageEvidenceParser:
    def parse_dir(self, directory: str | Path) -> list[Evidence]:
        path = Path(directory)
        if not path.exists():
            return []
        evidence: list[Evidence] = []
        for file_path in sorted(path.iterdir()):
            if file_path.suffix.lower() == ".json":
                evidence.extend(self.parse_sidecar(file_path))
        return evidence

    def parse_sidecar(self, path: str | Path) -> list[Evidence]:
        file_path = Path(path)
        payload = read_json(file_path)
        regions = payload.get("regions", payload) if isinstance(payload, dict) else payload
        evidence: list[Evidence] = []
        for index, region in enumerate(regions if isinstance(regions, list) else [], start=1):
            if not isinstance(region, dict):
                continue
            text = str(region.get("text") or region.get("description") or "")
            if not text:
                continue
            document_id = str(region.get("document_id") or file_path.stem)
            op_id = str(region.get("op_id") or "OP_UNKNOWN")
            evidence.append(
                build_evidence(
                    document_id=document_id,
                    op_id=op_id,
                    modality="drawing",
                    text=text,
                    source_file=str(region.get("image_file") or file_path),
                    bbox=[float(x) for x in region.get("bbox", [])],
                    page_index=region.get("page_index"),
                    field_name=str(region.get("region_type") or "image_region"),
                    value=text,
                    confidence=float(region.get("confidence", 1.0)),
                    metadata={"region_index": index, **region},
                )
            )
        return evidence
